spring:
  datasource:
    url: jdbc:mysql://localhost:3307/youbank
    username: root
    password: mysql502

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true
        order_updates: true
        show_sql: true

mybatis:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl --mybatis? ??? ??? ??? ? ???
    map-underscore-to-camel-case: true
    default-statement-timeout: 0 #???? ???? ?? ??? ????? 0? ??? ???
  # resources ?? ?? classpath ???? ???? ?? ??
  mapper-locations: classpath:/mappers/**/*.xml