spring:
  datasource:
    url: jdbc:mysql://192.168.0.144:3307/db_odd_adv_3
    username: odd_adv_3
    password: view502

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        #format_sql: true
        order_updates: true
        #show_sql: true

mybatis:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl --mybatis? ??? ??? ??? ? ???
    map-underscore-to-camel-case: true
    default-statement-timeout: 0 #???? ???? ?? ??? ????? 0? ??? ???
  # resources ?? ?? classpath ???? ???? ?? ??
  mapper-locations: classpath:/mappers/**/*.xml